//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ItemVenda
{
	private int quantidade
	{
		get;
		set;
	}

	private double precoUnitario
	{
		get;
		set;
	}

	private Produto prod
	{
		get;
		set;
	}

	public virtual Produto Produto
	{
		get;
		set;
	}

	public virtual void calcularTotal()
	{
		throw new System.NotImplementedException();
	}

	public virtual void imprimirItem()
	{
		throw new System.NotImplementedException();
	}

}

