//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Produto
{
	private int codigoProduto
	{
		get;
		set;
	}

	private string descricao
	{
		get;
		set;
	}

	public virtual void imprimirProduto(object );string()
	{
		throw new System.NotImplementedException();
	}

}

