//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Venda
{
	private int codigoVenda
	{
		get;
		set;
	}

	private DateTime dataVenda
	{
		get;
		set;
	}

	private object itens[]Item
	{
		get;
		set;
	}

	private Cliente cliente
	{
		get;
		set;
	}

	public virtual IEnumerable<ItemVenda> ItemVenda
	{
		get;
		set;
	}

	public virtual void calcularTotal()
	{
		throw new System.NotImplementedException();
	}

	public virtual void imprimirVenda()
	{
		throw new System.NotImplementedException();
	}

}

